"""Run the three-session scenario and write a readable transcript.

    python scripts/demo_multi_session.py              # offline, reproducible
    python scripts/demo_multi_session.py --llm anthropic

Outputs:
    docs/sample_multi_session.md   human-readable transcript with traces
    results/transcript.json        machine-readable records
"""

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from memagent.evaluation.runner import run_scenario  # noqa: E402


def fmt_turn(r: dict) -> list[str]:
    t = r["trace"]
    out = [f"**User:** {r['message']}", "", "**Agent:** " + r["response"]]
    if r["citations"]:
        out += ["", "<sub>Sources:</sub>"]
        for c in r["citations"]:
            ref = c["ref"] if c["kind"] != "memory" else c["ref"][:160] + ("…" if len(c["ref"]) > 160 else "")
            out.append(f"<sub>[{c['tag']}] {ref} — relevance {c['score']:.2f}</sub>  ")
    notes = [f"retrieval: *{t['plan']['reason']}*"]
    if t["memory_writes"]:
        notes.append("memory: " + "; ".join(f"{w['action']} “{w['text']}”" for w in t["memory_writes"]))
    if t["steps_completed"]:
        notes.append("task: completed " + ", ".join(f"“{s}”" for s in t["steps_completed"]))
    if t.get("knowledge_optimiser"):
        o = t["knowledge_optimiser"]
        notes.append(f"optimiser: {o['input_items']}→{o['output_items']} chunks, {o['input_tokens']}→{o['output_tokens']} tokens "
                     f"(filtered {o['filtered']}, dup {o['near_dups'] + o['exact_dups']})")
    if t.get("session_compaction"):
        c = t["session_compaction"]
        notes.append(f"session compaction: folded {c['folded_turns']} messages, {c['tokens_before']}→{c['tokens_after']} tokens")
    notes.append(f"prompt: {t['context_total']} tokens")
    out += ["", "> " + "  \n> ".join(notes), ""]
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--llm", default="offline", choices=["offline", "anthropic", "auto"])
    ap.add_argument("--data-dir", default=str(ROOT / ".demo_state"))
    args = ap.parse_args()
    data_dir = Path(args.data_dir)
    if data_dir.exists():
        shutil.rmtree(data_dir)

    def live(r):
        if r["kind"] == "user":
            print(f"\nUSER: {r['message']}\nAGENT: {r['rendered']}")
        elif r["kind"] == "session_start":
            print(f"\n======== SESSION {r['session']} ({r['session_id']}) — upfront {r['upfront_tokens']} tokens ========")

    transcript = run_scenario(data_dir, ROOT / "data" / "knowledge", llm=args.llm, on_event=live)

    md = [
        "# Sample multi-session interaction",
        "",
        "Generated by `python scripts/demo_multi_session.py` "
        f"(generator: `{args.llm}`). Each session is run by a **new `MemoryAgent` instance** that shares "
        "nothing with the previous one except the on-disk stores (`session.sqlite`, FAISS indexes), "
        "so every piece of continuity below came through persistence.",
        "",
        "Scenario: Priya migrates the `orders-api` service from the legacy v1 platform to Nimbus over three sessions.",
        "",
        "Legend: `[S#]` = retrieved just-in-time, `[P#]` = pinned knowledge loaded upfront, `[M]` = long-term memory.",
        "",
    ]
    for session in transcript:
        start = session[0]
        md += [f"## Session {start['session']}  (`{start['session_id']}`)", ""]
        if start["upfront_sections"]:
            md += [f"**Upfront context loaded at session start** ({start['upfront_tokens']} tokens):", "", "```text"]
            for name, body in start["upfront_sections"].items():
                md += [f"## {name}", body]
            md += ["```", ""]
        else:
            md += ["*First session — nothing to load upfront yet.*", ""]
        if start.get("restored_task"):
            md += [f"Working memory restored from checkpoint: active task “{start['restored_task']}”.", ""]
        for r in session[1:]:
            if r["kind"] == "action":
                md += [f"*Agent action:* `start_task(\"{r['args'][0]}\", {len(r['args'][1])} steps)` "
                       "→ task stored in session memory, working memory set, fact written to long-term memory.", ""]
            elif r["kind"] == "user":
                md += fmt_turn(r)
            elif r["kind"] == "session_end":
                md += ["**Session end → consolidation**", "",
                       f"- Episode summary written to long-term memory: “{r['summary'][:300]}”",
                       f"- Working-memory snapshot checkpointed into the open task",
                       f"- Long-term memory write stats so far: `{r['ltm_stats']}`", ""]
    (ROOT / "docs" / "sample_multi_session.md").write_text("\n".join(md), encoding="utf-8")
    (ROOT / "results").mkdir(exist_ok=True)
    slim = [[{k: v for k, v in r.items() if k != "prompt"} for r in s] for s in transcript]
    (ROOT / "results" / "transcript.json").write_text(json.dumps(slim, indent=2, default=str), encoding="utf-8")
    # keep one full prompt as an example of the assembled context
    example = next(r for s in transcript[1:] for r in s if r["kind"] == "user" and r["citations"])
    (ROOT / "results" / "example_prompt.txt").write_text(example["prompt"], encoding="utf-8")
    print("\nWrote docs/sample_multi_session.md, results/transcript.json, results/example_prompt.txt")


if __name__ == "__main__":
    main()
